### ISSUE TITLE
Clearer "Usage" section needed

### ISSUE THREAD

**Issue by FelDev** [hansottowirtz/cloudflare-workers-cache#1]
Hello and thank for creating this package!

I'm trying set it up and just want to point out the hurdles I get while reading the README

The "Usage" section contains this example:

```ts
import {
  cache,
  revalidateTag,
  provideCacheToFetch,
  createCfCacheObjectCache,
  createCfKvCacheTagStore,
} from "cloudflare-workers-cache"

const cacheConfig = {
  objectCache: createCfCacheObjectCache(caches.open("cache")),
  cacheTagStore: (env) => createCfKvCacheTagStore(env.CACHE_TAG_STORE),
}

const cachedSum = cache(sum, ["sum"], {
  tags: ["sum"],
})

export default {
  fetch: provideCacheToFetch(cacheConfig, async (req) => {
    const url = new URL(req.url)
    if (url.pathname === "/revalidate") {
      revalidateTag("sum")
      return new Response("Revalidated")
    }
    const a = +url.searchParams.get("a")!
    const b = +url.searchParams.get("b")!
    const result = await cachedSum(a, b)
    return new Response(result.toString())
  }),
}
```

Which I believe comes from example-app/src/index.ts

This is a bit confusing though, because if one copy/pastes the example above, one gets "Cannot find name 'sum'.ts(2304)"
![Screenshot 2024-04-18 at 14 12 37](https://github.com/hansottowirtz/cloudflare-workers-cache/assets/17578204/4e5edda7-42a0-4c4b-9211-bc81d515b055)

---

Another detail that could be made clearer is this line
`kv_namespaces = [{ binding = "CACHE_TAG_STORE", id = "<id>" }]`
What is `<id>` supposed to be? Does it matter? Or is it literally "\<id\>"?

---

I might open a PR once I get this thing to work, just wanted to point out what's confusing for a newcomer.

Thanks again!

**Comment by hansottowirtz** [comment]
Hi! Thank you for your comment! I didn't spend too much time on the Readme yet, I can make things clearer for sure.

`<id>` -> you will get this id when you're creating the kv namespace using `wrangler kv:namespace create CACHE_TAG_STORE`

For the `sum` function, this is just an example of a function you can cache:
```ts
function sum(a: number, b: number) { return a + b }
```

I will clear these things up, if you have further questions let me know!
